server:
  port: 10020
  servlet:
    context-path: /cleaner


#环境选择配置
spring:
  profiles:
    active: pro

#系统信息
cn:
  wolfshadow:
    system:
      swager-config:
        project-name: GoldSpider-数据清洗模块
        description: 负责从html文件中清洗需要的数据
        version: 1.0-SNAPSHOT
        service-terms: http://www.wolfshadow.cn
        author: WolfShadow
        link-text: WolfShadow主页
        website: http://www.wolfshadow.cn
      quartz:
        start-clean-seconds: 60
        file-batch-count: 10
        html-save-path: D:/File/gold_spider/html
        excel-save-path: D:/File/gold_spider/excel