server:
  port: 10010
  servlet:
    context-path: /digger

#环境选择配置
spring:
  profiles:
    active: pro

#系统信息
cn:
  wolfshadow:
    system:
      swager-config:
        project-name: GoldSpider-挖掘模块
        description: 负责爬取页面
        version: 1.0-SNAPSHOT
        service-terms: http://www.wolfshadow.cn
        author: WolfShadow
        link-text: WolfShadow主页
        website: http://www.wolfshadow.cn
      quartz:
        task-create-seconds: 60
        task-count: 1
        html-save-path: D:/File/gold_spider/html